name: Build Windows EXE

# 수동·push·PR 모두 트리거할 수 있게 설정
on:
  workflow_dispatch:     # 수동 실행
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Clean build folders
        run: |
          rmdir /S /Q build  || echo no build folder
          rmdir /S /Q dist   || echo no dist folder

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller \
            --onefile \
            --name mh-bills \
            --workpath build \
            --distpath dist \
            main.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: mh-bills-windows
          path: dist/mh-bills.exe
